### ISSUE TITLE
missing public api(maybe just docs) of gen

### ISSUE THREAD

**Issue by krzysztofpniak** [francisrstokes/Lazy-Infinite-List#2]
[Avaq](https://github.com/Avaq) posted really interesting solution for my problem using Lazy-Infinite-List: https://github.com/fluture-js/Fluture/issues/421#issuecomment-603883987
Anyways it seems he used not documented `gen` property. I would like to know if it is safe to use.
If yes I think it's a good idea to put it into public api and docs.

**Comment by Avaq** [comment]
It came up again today in https://github.com/fluture-js/Fluture/issues/477
